version: '3.9'

services:
  efclub_django:
    container_name: efclub_django
    image: bibared/efclub:efclub_django-${EFCLUB_DJANGO_VERSION}
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py shell < createadmin.py &&
             gunicorn --env DJANGO_SETTINGS_MODULE=efclub_django.settings -b 0.0.0.0:8000 -w 3 efclub_django.wsgi"
    env_file:
      - ./.env
    ports:
      - '8000:8000'
    volumes:
      - ./efclub_django/logs:/app/logs
  group_bot:
    image: bibared/efclub:group_bot-${GROUP_BOT_VERSION}
    container_name: group_bot
    env_file:
      - ./.env
    volumes:
      - ./group_bot/logs:/app/logs
      - ./db:/app/db
    depends_on:
      - efclub_django
