# Generated by Django 4.0.4 on 2022-05-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='id канала')),
                ('channel_id', models.BigIntegerField(unique=True, verbose_name='id канала')),
            ],
            options={
                'db_table': 'channels',
            },
        ),
        migrations.CreateModel(
            name='GetcourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_group_id', models.CharField(default='', max_length=255, verbose_name='id группы лист ожидания')),
                ('club_group_id', models.CharField(default='', max_length=255, verbose_name='id группы члены клуба')),
            ],
            options={
                'db_table': 'group_get_course',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id группы')),
                ('name', models.CharField(max_length=255, verbose_name='id канала')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='MessageNewStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting', models.TextField(blank=True, verbose_name='Текст после регистрации в листе ожидания')),
                ('entered', models.TextField(blank=True, verbose_name='Текст после вступления в клуб')),
                ('returned', models.TextField(blank=True, verbose_name='Текст после возвращения в клуб')),
                ('excluded', models.TextField(blank=True, verbose_name='Текст после исключения из клуба')),
                ('privileged', models.TextField(blank=True, verbose_name='Текст после получения привилегий')),
            ],
            options={
                'verbose_name': 'сообщение о новом статусе',
                'verbose_name_plural': 'сообщения о новом статусе',
                'db_table': 'messages_new_status',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TextField(verbose_name='Текст в основном меню')),
                ('about', models.TextField(verbose_name='Текст о клубе')),
                ('prices', models.TextField(verbose_name='Текст с ценами')),
                ('reviews', models.TextField(verbose_name='Текст с отзывами')),
                ('for_mailing', models.TextField(verbose_name='Текст в рассылки на оплату')),
                ('for_invite', models.TextField(verbose_name='Текст вместе с инвайт ссылками')),
                ('for_get_phone', models.TextField(verbose_name='Текст с запросом контакта')),
                ('for_challenger', models.TextField(verbose_name='"Хочу в клуб" новичков')),
                ('for_waiting_list', models.TextField(verbose_name='"Хочу в клуб" для листа ожидания')),
                ('for_excluded', models.TextField(verbose_name='"Хочу в клуб" исключенных')),
                ('for_entered', models.TextField(verbose_name='"Хочу в клуб" для тех кто может получить ссылку')),
                ('for_entered_got_link', models.TextField(verbose_name='"Хочу в клуб" для тех кто уже получал ссылку')),
                ('link_waiting_list', models.CharField(max_length=255, verbose_name='Ссылка на лист ожидания')),
                ('link_to_pay', models.CharField(max_length=255, verbose_name='Ссылка на оплату')),
            ],
            options={
                'verbose_name': 'Текст в меню',
                'verbose_name_plural': 'Тексты в меню',
                'db_table': 'text_messages',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getcourse_id', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='id пользователя в getcourse')),
                ('phone', models.CharField(max_length=255, unique=True, verbose_name='телефон')),
                ('telegram_id', models.BigIntegerField(default=None, null=True, unique=True, verbose_name='id пользователя в телеграмм')),
                ('status', models.CharField(choices=[('challenger', 'претендент'), ('waiting', 'В листе ожидания'), ('excluded', 'исключен'), ('entered', 'Вступил'), ('returned', 'Вернулся после исключения'), ('privileged', 'Привилегированный')], max_length=50, verbose_name='Статус пользователя')),
                ('status_updated', models.BooleanField(default=True, verbose_name='Обновлен статус')),
                ('got_invite', models.BooleanField(default=False, verbose_name='Получал инвайт ссылку')),
                ('expiration_date', models.DateTimeField(auto_now=True, verbose_name='Дата окончания привилегии')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting', models.TextField(verbose_name='Сообщение при попадании в список ожидания')),
                ('entered', models.TextField(verbose_name='Сообщение при вступлении в клуб')),
                ('returned', models.TextField(verbose_name='Сообщение при возвращении в клуб после исключения')),
                ('excluded', models.TextField(verbose_name='Сообщение при исключении из клуба')),
                ('got_invite', models.TextField(verbose_name='Сообщение при повторном запросе ссылки')),
            ],
            options={
                'db_table': 'user_status',
            },
        ),
    ]
