# Generated by Django 4.0.4 on 2022-05-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joining_club',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата записи о вступлении'),
        ),
    ]
