# Generated by Django 4.0.4 on 2022-05-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_user_date_joining_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joining_club',
            field=models.DateTimeField(verbose_name='Дата записи о вступлении'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, default=None, null=True, unique=True, verbose_name='id пользователя в телеграмм'),
        ),
    ]
