# Generated by Django 4.0.4 on 2022-05-30 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_alter_user_date_joining_club_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 9, 8, 12, 407391), verbose_name='Дата окончания привилегии'),
        ),
    ]
