# Generated by Django 4.0.4 on 2022-05-30 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0004_alter_user_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 9, 11, 49, 141535, tzinfo=utc), verbose_name='Дата окончания привилегии'),
        ),
    ]
