# Generated by Django 4.0.4 on 2022-05-30 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0005_alter_user_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания привилегии'),
        ),
    ]
